version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health_help_app
    volumes:
    - ./src/main/resources/script:/docker-entrypoint-initdb.d